######### Variables ###########
variable "app_ami" {}
variable "app_instance_type" {}
variable "ssh_key_pair" {}
variable "prefix" {}
variable "lb_security_group" {}
variable "web_port" {}
variable "web_security_group" {}
variable "web_subnets" {}
variable "vpc_cidr" {}
